<?php

		/**
		 * room_id is generated from the random text generated by the uniqid() function
		 * and the date is generated by the date() function with format (YmdHis)
		 * the sha1() function is used to hash the room_id
		 * the room_id is used to identify the room in the database
		 */
		$randomText = uniqid();
		$date = date('YmdHis');
		$room_id = sha1($randomText);
		
		echo "Room ID: " . $room_id . "<br>";

		?>